---

# GitHub workflow to test changes (as in pull requests) on any of my GitHub repositories

name: Basic change testing


# Without quotes, this key could be parsed as the boolean true value instead of the string "on"
'on':
  workflow_call:


jobs:
