---

# GitHub workflow to test changes (as in pull requests) on my GitHub repositories hosting Python apps

name: Python app change testing


# Without quotes, this key could be parsed as the boolean true value instead of the string "on"
'on':
  workflow_call:


jobs:
